### ISSUE TITLE
pose animation

### ISSUE THREAD

**Issue by armheb** [RenYurui/Global-Flow-Local-Attention#10]
Great paper and repo. are you planning to release the code for the pose based animation generation? 
how should we use the keypoints to input the model?
Thank you so much.

**Comment by RenYurui** [comment]
Thanks for your interest.
We are trying to refine the pose animation model. The code and trained model will be released once it is finished. 
We convert the keypoints to heatmaps to input the model, which is similar to the preprocessing of the pose image generation task.

**Comment by armheb** [comment]
Thanks, looking forward to it.
