### ISSUE TITLE
face animation result

### ISSUE THREAD

**Issue by lyupei** [RenYurui/Global-Flow-Local-Attention#11]
hi, I run the test code of face animation with the supplied checkpoint file and FaceForensics dataset, but I got some horrible result such as extra eyes. It happens even with the video you show in the REASDME.

BTW, I'm using the 1080Ti card, and got "cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1019UndefinedTensorImpl10_singletonE" error when "import resample2d_cuda", so I modified the "include <torch/torch.h>" to "include <torch/extension.h>" and it works.

**Comment by RenYurui** [comment]
Cloud you please give me more details?
Have you built the CUDA Modules successfully? If you use 1080Ti you may want to comment the 
``` python
    '-gencode', 'arch=compute_70,code=sm_70',
    '-gencode', 'arch=compute_70,code=compute_70'
```
in the setup.py files of these modules. And use sm50, sm52, sm60, sm61.

In addition, please check you data. It is correct? For example, we crop the videos to remove the background. And we use face keypoints as the additional information.

**Comment by lyupei** [comment]
hmm, I think maybe some preprocess will help.
Is there any gudiance? should I apply a mask to remove all background or just crop?

**Comment by RenYurui** [comment]
We just crop the videos. You can follow the steps [here](https://github.com/RenYurui/Global-Flow-Local-Attention/blob/master/IMAGE_ANIMATION.md#dataset-preparation).

**Comment by lyupei** [comment]
ok, 3ks for your reply.
Great work, looking forward to the pose animation code.
