### ISSUE TITLE
How to comprehend 'force the attention coefficient matrix to be a sparse matrix' in paper?

### ISSUE THREAD

**Issue by lscelory** [RenYurui/Global-Flow-Local-Attention#12]
Hello,
Thanks for your nice work!
After reading your paper, I'm confused about the 'sparse matrix' in your paper. This matrix are the attention coefficient at a certain location ([n, n, 1] in paper) or the whole attention map of the feature? And why under your architecture and loss this matrix is sparse finally?
Hoping your can give me some guidance, Thanks again!

**Comment by RenYurui** [comment]
Thanks for your interest.
In our paper, we claim that the Attention Coefﬁcient Matrix between the source and target should be a sparse matrix in this task. This attention matrix here is the whole attention map.

Specifically, let us denote the source as f_s (with resolution as n*n). The target feature is denoted as f_t (n*n). Then the Attention coefﬁcient matrix A (with resolution as n^2 * n^2) describes the attention correlations between source features and target features.


Our Global-flow Local-Attention can be seen as an attention method. The attention coefﬁcients of the features which are not sampled are zeros. Therefore, the attention matrix is a sparse matrix.

We compare our method with the Global-Attn model (which has a dense attention matrix) in our ablation study. You can refer to Fig6 in our paper for details.

**Comment by lscelory** [comment]
Sorry for replying late, thank you for the detailed explanations! @RenYurui
