### ISSUE TITLE
ImportError:undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

### ISSUE THREAD

**Issue by maoyali** [RenYurui/Global-Flow-Local-Attention#15]
Hi, I run your test code but meet some error:
ImportError: /home/ttt/.local/lib/python3.7/site-packages/resample2d_cuda-0.0.0-py3.7-linux-x86_64.egg/resample2d_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
Could you give me some advice?

**Comment by fengzz-coding** [comment]
I have the same problem, can you tell me how to avoid it? 
BTW, I'm using the NVIDIA T4
