### ISSUE TITLE
There are some problem on the car checkpoint

### ISSUE THREAD

**Issue by maoyali** [RenYurui/Global-Flow-Local-Attention#16]
Hello, Thanks for your handsome work! I have tested your pretrained model on the shapenet. It woks well on the chair dataset . But the predict result on the car dataset is wrong:
![result_0000](https://user-images.githubusercontent.com/31682925/76840027-80d11280-6871-11ea-9f96-b85c9f74c2ba.png)
I just used the same code with their respective checkpoint. Could you give me some advice?

**Comment by RenYurui** [comment]
I have checked my checkpoints and code. I did not reproduce the error. Please check your project:
1. is the model loaded successfully?
2.is the data load correctlly?

**Comment by maoyali** [comment]
Thanks for your help.
