### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Ha0Tang** [RenYurui/Global-Flow-Local-Attention#17]
----------------End----------------
Loading data pairs ...
Loading data pairs finished ...
dataset [MarketDataset] of size 12000 was created
testing images = 12000
Network [PoseGenerator] was created. Total number of parameters: 12.9265 million. To see the architecture, do print(network).
Network [ResDiscriminator] was created. Total number of parameters: 0.2382 million. To see the architecture, do print(network).
model resumed from latest iteration
load G from latest_net_G.pth
load D from latest_net_D.pth
model [Pose] was created
test_market.sh: line 2: 37710 Segmentation fault      (core dumped) python test.py --name=pose_market_checkpoints --model=pose --attn_layer=2 --kernel_size=2=3 --gpu_id=0 --dataset_mode=market --dataroot=./dataset/market --results_dir=./eval_results/market

**Comment by Honlan** [comment]
I met the problem of segmentation fault as well.

**Comment by Eliot04** [comment]
Could you please explain the issue for the public as well?
