### ISSUE TITLE
Do I need to normalize the scale of key points?

### ISSUE THREAD

**Issue by scparktop** [RenYurui/Global-Flow-Local-Attention#18]
Thank you for your great project.

**1. the label order**
In 'pose_utils.py'
 LABELS = ['nose', 'neck', 'Rsho', 'Relb', 'Rwri', 'Lsho', 'Lelb', 'Lwri',
               'Rhip', 'Rkne', 'Rank', 'Lhip', 'Lkne', 'Lank', **'Leye', 'Reye', 'Lear', 'Rear'**]

I think LABELS should be
 LABELS = ['nose', 'neck', 'Rsho', 'Relb', 'Rwri', 'Lsho', 'Lelb', 'Lwri',
               'Rhip', 'Rkne', 'Rank', 'Lhip', 'Lkne', 'Lank', **'Reye', 'Leye', 'Rear', 'Lear'**]

**2. the scale of key points**
I'm training with some images which are bigger than the images in Market1501.
My images are in the (100 X 300) ~ (400 X 1000) range.
The visdom web page shows my images very well.
But, it shows just black or just some parts of the key points of the images in 'input_BP1' window and 'input_BP2' window.
Do I need normalize the scale of the key points to train?

**Comment by RenYurui** [comment]
Yes, you need to normalize your key points
We have functions to help you to finish this operation.
You may want to refere to the function "obtain_bone" in base_dataset.py. 
To obtain the keypoint map
``` python
pose_utils.cords_to_map(array, load_size, old_size, affine_matrix)
```
Where "load_size" is the training image size of your network.
"old_size" is the original image size (the image size when you use to extract the skeletons)

**Comment by scparktop** [comment]
Thank you for your detailed explanation.
I found that the key point scale is different from image scale.
(looks like 256/1101 scale of image size)
'pose_utils.cords_to_map()' is the key.
I'll check and try.
Thank you ^ ^
