### ISSUE TITLE
 Pose-Guided Person Image Animation

### ISSUE THREAD

**Issue by starHu123** [RenYurui/Global-Flow-Local-Attention#19]
Could you upload the code and trained models of Pose-Guided Person Image Animation？Please.

**Comment by RenYurui** [comment]
Thanks for your interest.
We really want to update the code as soon as possible. However, this project is under development currently. 
We will update the code once it is done.

**Comment by annopackage** [comment]
Hi, could you kindly share some tricks regarding how to make video results better? Another fundamental question, could you tell me how to insert GIF / video clip into pdf using latex or overleaf? Thanks in advance.

**Comment by eladrich** [comment]
Hi,
The paper looks really great! I was wondering whether there is an update regarding this specific model.

Best,
Elad

**Comment by RenYurui** [comment]
Thanks for your interest.
Yes! We are preparing the code now. 
The updates will be provided in the next few days.

**Comment by eladrich** [comment]
Awesome!! Thanks for the quick reply, can't wait to try it out :)

**Comment by RenYurui** [comment]
Hi all,
We have uploaded the code of the pose-guided person image animation task. Please find the details in the README.md. 
Let me know if you encounter any problems.
