### ISSUE TITLE
Are Keypoints Neccessary For Image Animation?

### ISSUE THREAD

**Issue by ftaker887** [RenYurui/Global-Flow-Local-Attention#2]
Hello, thanks for releasing this project. I have my own dataset that would be considered "in the wild", but there are no keypoints. Would it be possible to train without having keypoints, or are they necessary? If so, what would be the best way to gather keypoints for training on our own datasets? Thanks!

**Comment by RenYurui** [comment]
I think it is necessary to provide reasonable structural guidance information for the network. In addition to keypoints, this information can also be edge maps, viewpoints, and even hidden variables. 

If your video is about the actions of persons, keypoints may be a good choice. You can use some keypoints extractors such as [Alphapose](https://github.com/MVIG-SJTU/AlphaPose) and [Openpose](https://github.com/CMU-Perceptual-Computing-Lab/openpose) to obtain keypoints from your videos.

**Comment by ftaker887** [comment]
That answers it perfectly. Thanks!
