### ISSUE TITLE
separate reference image for face animation

### ISSUE THREAD

**Issue by eps696** [RenYurui/Global-Flow-Local-Attention#21]
hello,
as far as i could see, your face animation code uses the first frame of the video as a reference, and the whole video for an animation guidance. alas, i've failed to find any option in your code to split reference and guidance (which is obviously the most reasonable thing to try). could you advice please, where to look and what to change, to load standalone (separate) reference image?
thanks in advance

**Comment by RenYurui** [comment]
Yes, we use the first frame as the reference image in the test phase.  When we train the model, video clips are randomly loaded. We use the first frame of the video clips as the reference. It will cause some problems when you want to use an arbitrary reference image.

To split the reference images, you need to modify  "face_dataset.py" and "face_model.py". These two files are used to define the data_loader and the model_training of the face animation task.
You may want to first randomly select an image frame from a loaded video as the reference image (modify the "face_dataset.py" ). And then modify the "set_input" function in "face_model.py" (self.P_reference and self.BP_reference are the image and skeleton of reference image).

**Comment by eps696** [comment]
thank you, will explore that

**Comment by Maxi1000dp** [comment]
Hello! the project looks very interesting. But I am having trouble doing what is suggested in this issue. I was exploring face_model.py and other files, but failed to test with an image from a different source than the video.

It would be great to have an example or command that receives on the one hand a source image and on the other the video that is the reference of the animation
Could you help me?

**Comment by RenYurui** [comment]
Hi
The face animation task is only trained to recover video clips currently. It means that the guidance edges comes from the same person with the source image.  
You may need to normalize the face key points and carefully due with the background edge (remove the background edge for example) if you want to animate different sources.

**Comment by Maxi1000dp** [comment]
thanks Ren! now I understand and I will continue to explore.
This is a great job. Cheers
