### ISSUE TITLE
Abot the visualization results of different attention modules

### ISSUE THREAD

**Issue by BaldrLector** [RenYurui/Global-Flow-Local-Attention#24]
@RenYurui 
Hi:
Great work! 
I have a problem with the Fig.6 the attention visualization part. This part in the paper is short,
could you explain how to get the attention map from the target region to the corresponding source region? ( col of 6, 8 Fig.6 )
Is there any code for reference?

Thank you, your reply will be very appreciated

**Comment by RenYurui** [comment]
We visualize the flow fields/attention matrix.
For example, for the full model attention map (col 8), we extract the flow fields and local attention coefficients.
For each target position, a local source region is assigned (3x3 or 5x5) according to the flow fields. The sampling coefficients is calculated by the local attention module. Therefore, we can draw a mask for each target position.
Masks of all target positions in the red rectangles are summed the get the final maps.

**Comment by BaldrLector** [comment]
Thanks for your clarification,
I am still confused. 
Since there are many attention maps ( different spatial sizes),  for each attention map we can perform back-warping. Could you clarify how you fuse all those attention maps, or you just use one attention map here?
Thank you. And if convenient, could you share this part code?

**Comment by BaldrLector** [comment]
Thanks for your clarification,
I am still confused. 
Since there are many attention maps ( different spatial sizes),  for each attention map we can perform back-warping. Could you clarify how you fuse all those attention maps, or you just use one attention map here?
Thank you. And if convenient, could you share this part code?

**Comment by RenYurui** [comment]
We use the flow fields at resolution 64 in Fig 6. 
You can use the following example code:
```python
attn_param = np.load(attn_path) # local atention coefficients
flow_field = np.load(flow_path) # the corresponding flow fields

visi=np.zeros((flow_field.shape[1],flow_field.shape[2]))
x_start, x_end, y_start, y_end = get_rectangle() # obtain the positions of red rectangle
kz = int(attn_param.shape[0]**0.5)
size = int(kz/2)

for x in range(x_start, x_end):
    for y in range(y_start, y_end):
        offset = flow_field[:,y,x]
        delta_x = (x+offset[0]-math.floor(x+offset[0])) # the bilinear sampling parameter
        delta_y = (y+offset[1]-math.floor(y+offset[1]))  # the bilinear sampling parameter          
        for i in range(-size, size):
            for j in range(-size, size):
                # obtain the bilinear sampling coordinates
                x_left = max(min(int(math.floor(x+offset[0]+j)), flow_field.shape[1]-1),0)  
                x_right = max(min(int(math.floor(x+offset[0]+j)+1), flow_field.shape[1]-1),0)
                y_top = max(min(int(math.floor(y+offset[1]+i)), flow_field.shape[1]-1),0)
                y_bottom = max(min(int(math.floor(y+offset[1]+i)+1), flow_field.shape[1]-1),0)

                visi[y_top, x_left] += (1-delta_x)*(1-delta_y) * attn_param[i*kz+j,y,x]
                visi[y_top, x_right] += delta_x*(1-delta_y) * attn_param[i*kz+j,y,x]
                visi[y_bottom, x_left] += (1-delta_x)*delta_y * attn_param[i*kz+j,y,x]
                visi[y_bottom, x_right] += delta_x*delta_y * attn_param[i*kz+j,y,x]
```
You can use the code as reference.

**Comment by BaldrLector** [comment]
Thanks for your kind replying.

**Comment by pfeducode** [comment]
get_rectangle()  is not been defined

**Comment by pfeducode** [comment]
what does  flow_field mean？
can you give  attn_param and flow_field  a random value to help me  understand it
