### ISSUE TITLE
About the number of iterations and convergence value when flow estimator converges

### ISSUE THREAD

**Issue by tangjilin** [RenYurui/Global-Flow-Local-Attention#25]
@RenYurui  Great work!
Recently I use your given default parameters to train the flow field estimator. I find the loss function curve quickly converges to a value approximately equal to **2**.
I want to know **the number of iterations and the convergence value** when your flow field estimator converges in your experiment.  
And when should I terminate the training of the flow field estimator and start training the overall network in end2end way?
Look forward to your reply. Thanks.
![image](https://user-images.githubusercontent.com/35884085/81259399-73aef380-906a-11ea-8631-948b9ff013f3.png)

**Comment by RenYurui** [comment]
Hi!
We found the sampling correctness loss decrease even after millions of iterations. 
For the Fashion dataset, we stop the training when the loss is roughly 2. 
For the Market dataset, we stop the training when the loss is roughly 1.5.
However, these values are only empirically set.

**Comment by tangjilin** [comment]
Got it. Thanks very much!
