### ISSUE TITLE
About the difference between img_highres.zip and img.zip about the DeepFashion dataset

### ISSUE THREAD

**Issue by tangjilin** [RenYurui/Global-Flow-Local-Attention#26]
@RenYurui  Hi! 
I have a question about the DeepFashion dataset.  In your experiment, you use the images of  img_highres.zip of the DeepFashion Dataset from In-shop Clothes Retrieval Benchmark to train the network.  Because I am waiting for the password from the dataset maintainers, I can't check the images in the img_highres.zip now. 
Can you tell me the difference between the images from img_highres.zip and img.zip located on the Google Drive?  Thanks!
![image](https://user-images.githubusercontent.com/35884085/81389914-30798100-914d-11ea-8a57-27fad98f5c7a.png)

**Comment by RenYurui** [comment]
Hi!
we provide some example images of the 'img_highres.zip' in our demo datasets. Please check these images by downloading the provided resources using 
``` bash
./download.sh
```

**Comment by tangjilin** [comment]
Hi. Thanks for your reply.  One more question.
Now I have got the example images in the 'img_highres.zip', which have a resolution of **750 x 1101**.
Meanwhile, the key points annotations that you used are extracted based on the resolution of **176 x 256.**
In your experiment, you resize the input images to 256 x 256 and normalize the key points to 256 x 256 as:
                   pose_utils.cords_to_map(array, load_size, old_size, affine_matrix)

However, the aspect ratio(width/length) of 750x1101 is different from that of 176x256. Thus, will using the images with resolution of 751x1101 as input cause the misalignment of key points in the images? The normalized key points may exist an offest?
Thanks.

**Comment by RenYurui** [comment]
Hi!
I do not think the different aspect ratios will lead to problems. We normlize the keypoints to [0,1] and then reproject them to correct image size.
However, if you find any bugs, please rease a pull request or report here.
