### ISSUE TITLE
Suggestion: Specify openpose format for AlphaPose instructions

### ISSUE THREAD

**Issue by andrewjong** [RenYurui/Global-Flow-Local-Attention#29]
Hi,

I just wanted to suggest that in this [documentation](https://github.com/RenYurui/Global-Flow-Local-Attention/blob/master/PERSON_IMAGE_ANIMATION.md) to specify that the AlphaPose output format should in fact be set to `--format open`. I just ran Alphapose on my test dataset, but realized that Alphapose by default outputs its own custom format, and not Openpose's format like is used in this repository.

Thanks,
Andrew

**Comment by RenYurui** [comment]
Hi!
Thanks for your suggestions.
I will update the document to provide more detailed instructions.
