### ISSUE TITLE
Why the poseflownet_model has no relation with pose_model?

### ISSUE THREAD

**Issue by lgqfhwy** [RenYurui/Global-Flow-Local-Attention#30]
As the paper said. the gloabl flow field estimator do: w, m = F(Xs, Ps, Pt), and the local neural texture renderer do : Xt = G(Xs, Pt, w, m). So as the paper, we should first train global flow field estimator, obtain w, m. Second we train local neural texture rendered.

But in the code, I found that in pose_model.py, it always input P1, BP1, BP2, which has no relation with the first stage global flow field network in poseflownet_model.py. In shapenetflow_model and shapenet_model also exist same problem.

So does this is a error in code or other reason? I am looking forward to your reply, Thank you so much!

**Comment by RenYurui** [comment]
Hi!
It is not an error. In the second stage, we train the whole model in an end-to-end manner. Therefore, the pose model contains the flow field estimator. Please check the `network.py` for more details
