### ISSUE TITLE
Pose-Guided Person Image Animation for arbitrary source image and poses.

### ISSUE THREAD

**Issue by armheb** [RenYurui/Global-Flow-Local-Attention#31]
Thanks for the great demo notebook. but I'm not sure if I want to generate an animation from my custom data how many images do I need? for example if I have a single source image and poses of each frame of an animation, will I be able to animate the source image?

**Comment by RenYurui** [comment]
Yes, in theory, these data are enough.
However, cause the model is trained using specific datasets with limited data distribution. Directly apply the model to custom images may lead to performance degradation. Therefore, if you have a dataset, please try to fine-turn or re-train the model in your own dataset.

**Comment by armheb** [comment]
Thanks for your explanation.
