### ISSUE TITLE
Help with poor results on my data?

### ISSUE THREAD

**Issue by andrewjong** [RenYurui/Global-Flow-Local-Attention#32]
Hello,

I finally got GFLA working on my own test data with your help, thanks very much! However, the output I am obtaining looks quite noisy.

![output1](https://user-images.githubusercontent.com/8121216/81895146-76c44b00-9566-11ea-8d81-cf3403bda0c3.gif)
![output2](https://user-images.githubusercontent.com/8121216/81895150-788e0e80-9566-11ea-80e2-3e30170d7f59.gif)

Would you have suggestions on how I can improve output? I am guessing the right-most pose is the result of the Motion Extraction Net. I ran the Motion Extraction Net using your provided pretrained-weights, but it looks somewhat noisy, and may be a leading cause of the issue.

**Comment by RenYurui** [comment]
Hi!
Currently, our model can not be directly used to deal with in-the-wide images and motions. Training a model that can animate custom images with custom motions is a challenging task to be solved in this field.

As for your question, I do not think the extracted skeletons are the main reasons for the poor results.
As explained [here](https://github.com/RenYurui/Global-Flow-Local-Attention/issues/31), the model is trained using specific datasets with limited data distribution. 
Therefore, poor results are obtained on actions that differ greatly from them.
To improve the performance:
1. fine-tune or re-train the model on your dataset
2. train the model using a richer dataset or find some ways to improve the generalization.


Same reasons for the Motion Extraction Net. Meanwhile, the motion extraction net obtains clean results using the skeleton sequence (use more than 80 frames to predict one frame). Therefore, it may fail with short videos or videos with greatly different fps.

**Comment by andrewjong** [comment]
Makes sense. Thanks for your help! I will try what you suggested and update here with what I find.

**Comment by andrewjong** [comment]
@RenYurui are there training instructions available for Person Animation, please? I only see Testing instructions on the [Person Image Animation](https://github.com/RenYurui/Global-Flow-Local-Attention/blob/master/PERSON_IMAGE_ANIMATION.md) page. Thanks!

**Comment by RenYurui** [comment]
Hi!
Sorry about the incomplete document of the person animation task. I will update the page in the next few days.
 
To train our model, you may need to first obtain clean skeletons using the Motion Extraction Net and then train the model using 
``` bash
python train.py \
--name=[name of your experiment] \
--model=dance \
--attn_layer=2,3 \
--kernel_size=2=5,3=3 \
--gpu_id=0,1 \
--dataset_mode=dance \
--sub_dataset=[your sub dataset] \
--dataroot=[your dataset root path] 
```
You may want to check the `dance_model.py` for the defination of the model and `dance_dataset.py` for the defination of the data loader.

**Comment by andrewjong** [comment]
Hi @RenYurui , approximately how many epochs/steps did it take you to get decent-looking results? I want to make sure that I catch the training process early on if there's something wrong with my data.

**Comment by andrewjong** [comment]
Also, do I need to re-train the Motion Extraction Net if I want clean pose results? Currently I am just using your provided pretrained weights. Is re-training necessary, or should it be sufficient to use it pretrained?

I ask because the poses appearing from my training data (extracted by the Motion Extraction Net?) look quite bad. The pose is sometimes distorted in strange ways.

![Screenshot_20200526_1718091](https://user-images.githubusercontent.com/8121216/82963259-378af680-9f77-11ea-97d7-070e341f58cc.png)
![Screenshot_20200526_1717201](https://user-images.githubusercontent.com/8121216/82963260-378af680-9f77-11ea-8d7b-28f670d79642.png)

If I do have to retrain, does that mean I need to create my own Motion-Extraction training data from the Human3.6M dataset?

Thanks.

**Comment by RenYurui** [comment]
Hi
You do not need to retrain the Motion Extraction Net. This net is trained using the Human36M dataset, which means that one can not fine-tune this net using a custom dataset.

I found your dataset change dramatically in human size. I think it may be the reason for the poor smooth results. (cause the data in Human36M maintains its spatial size for short sampling windows)

Anyway, as the Motion Extraction Net is an auxiliary network, you can try to use the extracted key points directly. (This may lead to performance degradation but you can also obtain reasonable results.) To do so, you need to change the `dir_B_clean` ( in `dance_dataset.py`) to the same directory as the noise keypoints. (Note: the flag `is_clean_pose` also need to be changed to False when you `load_skeleton` and `load_keypoint`;  LIMB_SEQ=openpose_utils.LIMB_SEQ_COCO_17 when showing the results )

The model generates reasonable results after about 10000 iters in our experiments. 

You may also want to change the reference images (function `split_ref_gen`), reference images with similar size with your generated results will help with the training. 

good luck!
