### ISSUE TITLE
About the memory usage when evaluating over the DeepFashion dataset.

### ISSUE THREAD

**Issue by tangjilin** [RenYurui/Global-Flow-Local-Attention#33]
Hi.
I want to know how much the memory usage is when evaluating over the DeepFashion dataset in your experiment?
In my experiment, it seems ~30G memory is still not enough when evaluating over the DeepFashion dataset. The process is always been killed due to the OOM.
Thanks!

**Comment by RenYurui** [comment]
Hi!
We calculate the distributions of the real images over the training dataset in the evaluation code. All the training images are loaded at once. If you find that this code uses too much memory, please try to load the images with batches.
