### ISSUE TITLE
LPIPS is does not work

### ISSUE THREAD

**Issue by Meimeiainaonao** [RenYurui/Global-Flow-Local-Attention#35]
Thanks for your code.

 I have an error When I can test the LPIPS:

```
lpips_score = lips.calculate_from_disk(distorated_list, gt_list, sort=False)

distance = np.zverage(result)

avg = a.mean(axies)

ret  = ret.dtype.type(ret / rcount)

AttributeError: 'torch.dtype' object has o attribute 'type'.
```

Thanks for your help.

**Comment by RenYurui** [comment]
Hi! 
have you cloned the LPIPS repo? (see [here](https://github.com/RenYurui/Global-Flow-Local-Attention/blob/master/PERSON_IMAGE_GENERATION.md#evaluation) )
Can you provide more detailed error information?
