### ISSUE TITLE
how can I get these pose-stick mask pictures?

### ISSUE THREAD

**Issue by wanghongyu607** [RenYurui/Global-Flow-Local-Attention#36]
Excuse me.  how can I get these pose-stick mask pictures?
Such as:
<img width="170" alt="屏幕快照 2020-02-24 下午6 54 04" src="https://user-images.githubusercontent.com/43949229/82548704-4ac04f80-9b8e-11ea-889a-6d6a2ab7f1a0.png">

**Comment by RenYurui** [comment]
Hi!
You may want to check the `pose_utils.py`. Function "cords_to_map" can help you with that.
