### ISSUE TITLE
What is the minimum requirements for training image animation?

### ISSUE THREAD

**Issue by Lotayou** [RenYurui/Global-Flow-Local-Attention#44]
Hi, thanks for your marvelous work! I just have a problem when trying to train the image animation on my custom dataset, which has been resized to 256*256 in advance. However, it seems that even a 16GB card is not enough for this. 

I wonder what is the minimum requirements for training image animation? Also, is there anywhere I can modify to reduce the memory while not compromising the final result too much? Thanks!

**Comment by RenYurui** [comment]
Hi, 
We train the animation model using 2 GPUs. The default setting (with batch Size=2) uses less than 12GB memory (each).
If you train the model using batchSize=1. It will take around 10GB.
Please check your code. You may need to modify the parameter of `dance_dataset.py` which is the Dataloader of the pose-guided person animation model.
Or you can simply run the code:
``` bash
python train.py \
--batchSize=1 \
...
```

**Comment by Lotayou** [comment]
Thanks for the tip, the problem is solved! Closing this issue now.

**Comment by kikirizki** [comment]
How long to train the model?
