### ISSUE TITLE
How to run python test.py in your project code

### ISSUE THREAD

**Issue by wanghongyu607** [RenYurui/Global-Flow-Local-Attention#45]
Excuse me! I reproduce your project in Windows10 and pycharm, I have no Linux environment. And I couldn't find the python test.sh document, the script cannot run in terminal. Could you tell me how to test in Windows10 environment?Thanks a lot!
![image](https://user-images.githubusercontent.com/43949229/85117793-ff16c980-b251-11ea-96cb-c17466627d3b.png)

**Comment by RenYurui** [comment]
Hi!
We currently only run this code with Linux environments. Please refer to our [colab demo](https://github.com/RenYurui/Global-Flow-Local-Attention/blob/master/demo.ipynb) for more details.
