### ISSUE TITLE
Why setting betas to (0, 0.999)?

### ISSUE THREAD

**Issue by hiyyg** [RenYurui/Global-Flow-Local-Attention#46]
Why do you set beta1 to 0 for Adam? Is there any specific interpretation?

**Comment by RenYurui** [comment]
Hi!
I think there is no specific reason for the setting of this parameter.

**Comment by hiyyg** [comment]
Does 0 perform better than 0.9 in your case?

**Comment by RenYurui** [comment]
We did not train our model with beta1=0.9. Therefore, I cannot say which one is better.
