### ISSUE TITLE
How to generate video for my image?

### ISSUE THREAD

**Issue by benpaodewoniu** [RenYurui/Global-Flow-Local-Attention#49]
Thanks for your work.It's amazing.

I want to generate vide for my image.In fact, I want to know this code can fit on my picture.So I should put my image for which  
dir?Can I put one picture or a series of pictures?

When I put pictures,How to generate?

python demo.py or other?

Thank you!

**Comment by RenYurui** [comment]
Currently, our model can not be directly used to deal with in-the-wide images and motions. Training a model that can animate custom images with custom motions is a challenging task to be solved in this field.

However, if you have a similar source image with the training datasets(Fashion Video & iPER), you can try to replace the source image with your own image (see the definition of the Dataloader in `dance_dataset.py`) and run the model with demo.py. Or you may need to train the model with your own dataset.

**Comment by benpaodewoniu** [comment]
I'm Sorry.I don't understand.I try two day,but I have no work.

How to change params in dance_dataset.py to generate video for custom image.

**Comment by RenYurui** [comment]
Sorry for the delay.
A simple way is to build a new 'val_list.csv' file, where you can replace:
 `data_dic['A_paths']['ref']=Path_to_your_reference_image`
 `data_dic['B_paths']['ref']=Path_to_the_skeleton_of_your_ref_image` (extracted by Alphapose with openpose format)
And then reun demo.py as we provided in the colab demo file
