### ISSUE TITLE
Can we use custom guidence video to generate animation video?

### ISSUE THREAD

**Issue by Stephenfang51** [RenYurui/Global-Flow-Local-Attention#5]
Firstly, Thanks so much for this amazing project !

As the title said, can test.py support generating animation video with our own custom guidence video? cause I did not see any demo script this repo? Thank you so much.

**Comment by RenYurui** [comment]
You can follow the description [here](https://github.com/RenYurui/Global-Flow-Local-Attention/blob/master/IMAGE_ANIMATION.md) for Face Image Animation.

The details of the Pose-based human motion imitation will come soon. Additional effort is made to model the temporal consistency.

**Comment by armheb** [comment]
Thank you so much for the repo, looking forward to the details of the pose-based model.
