### ISSUE TITLE
What is the "train_A"?

### ISSUE THREAD

**Issue by veralauee** [RenYurui/Global-Flow-Local-Attention#51]
I used "./script/download_animation_skeletons.sh" to download the danceFashion dataset, and prepares to run "test.py" on dancefashion, following https://github.com/RenYurui/Global-Flow-Local-Attention/blob/master/PERSON_IMAGE_ANIMATION.md

It needs "train_A" in "test_256" and "train_256", but the downloaded data only contains "train_alphapose" and "train_video2d". Where should I download the "train_A"?

**Comment by RenYurui** [comment]
train_A contains the images of the animation dataset. Please first download the videos of the datasets, and then extract the images use the provided script `./script/extract_video_frames.py`. 
``` bash
python ./script/extract_video_frames.py \
--frame_root=./path/to/dataset/root/train_A \
--video_path=[path to the mp4 files] \
--anno_path=[path to the previously downloaded skeletons]
```
