### ISSUE TITLE
Question about equation (5) in your paper.

### ISSUE THREAD

**Issue by Becomebright** [RenYurui/Global-Flow-Local-Attention#52]
Thanks for your inspiring work. I am wondering if the equation (5) in the paper was wrong. 

Given <a href="https://www.codecogs.com/eqnedit.php?latex=T=AS" target="_blank"><img src="https://latex.codecogs.com/png.latex?T=AS" title="T=AS" /></a>, we are going to use the least-squares method to estimate A.

The loss function is:<a href="https://www.codecogs.com/eqnedit.php?latex=J(A)&space;=&space;\frac{1}{2}(T-AS)^T(T-AS)" target="_blank"><img src="https://latex.codecogs.com/png.latex?J(A)&space;=&space;\frac{1}{2}(T-AS)^T(T-AS)" title="J(A) = \frac{1}{2}(T-AS)^T(T-AS)" /></a>

Then, the derivative should be:<a href="https://www.codecogs.com/eqnedit.php?latex=\frac{\partial&space;J(A)}{\partial&space;A}&space;=&space;(AS-T)S^T&space;=&space;0" target="_blank"><img src="https://latex.codecogs.com/png.latex?\frac{\partial&space;J(A)}{\partial&space;A}&space;=&space;(AS-T)S^T&space;=&space;0" title="\frac{\partial&space;J(A)}{\partial&space;A}&space;=&space;(AS-T)S^T&space;=&space;0" /></a>

Thus, <a href="https://www.codecogs.com/eqnedit.php?latex=\hat{A}=TS^T(SS^T)^{-1}" target="_blank"><img src="https://latex.codecogs.com/png.latex?\hat{A}=TS^T(SS^T)^{-1}" title="\hat{A}=TS^T(SS^T)^{-1}" /></a>, which is different from what appeares on the paper, ie., <a href="https://www.codecogs.com/eqnedit.php?latex=\hat{A}&space;=&space;(S^TS)^{-1}S^TT" target="_blank"><img src="https://latex.codecogs.com/png.latex?\hat{A}&space;=&space;(S^TS)^{-1}S^TT" title="\hat{A} = (S^TS)^{-1}S^TT" /></a>

Could you please check it? Also, it would be great if you can provide some explanations of the AffineRegularizationLoss() implementation. Thanks a lot.

**Comment by RenYurui** [comment]
Thanks for your remind. 
It is a typo. Your result is correct.  I will try to correct this typo in the paper. 

The implementation details of the AffineRegularizationLoss:
Let us first use the following symbol (sorry for the inconvenient):
Y=Ab
where b is the affine transformation parameter, A is the source coordinate, and Y is the target coordinate.
Therefore, b=(AH * A)^{-1} * AH * Y
We want to solve:
 ||Y-Ab||_2^2 
= (Y-Ab)^H * (Y-Ab)
= (Y-A(AH * A)^{-1} * AH * Y)^H * (Y-A(AH * A)^{-1} * AH * Y)
=YH * (I-A(AH * A)^{-1} * AH)^H * (I-A(AH * A)^{-1} * AH) * Y
=YH * KH * K * Y
where K=(I-A(AH * A)^{-1} * AH)

The previous equation is calculated for each local patch. K is identical for each patch. 
Therefore, we use the convolution layer to implement it.

**Comment by Becomebright** [comment]
Thanks for your clear explanation. 

While reading your code, I found that you calculate the loss in two steps. You first use a convolution layer to calculate KH * K * Y, and then do YH * (KH * K * Y). But is it necessary? As YH * KH = (K * Y)H, I think we just need to calculate K * Y to get the loss. 

BTW, does "H" mean "transpose"? Why do you use H instead of T?

**Comment by RenYurui** [comment]
Hi, 
Your implementation is also correct. 
"H" means transpose. We use "H" to avoid confusion with other symbols. ie ”T_l in the paper“
