### ISSUE TITLE
about the FID score and LPIPS score of DeepFashion dataset.

### ISSUE THREAD

**Issue by shyern** [RenYurui/Global-Flow-Local-Attention#53]
I notice that the deepfashion dataset used in this paper is cropped to 176*256 following PATN. Then the image pair (source image & target image) is first resized to 256*256, then this pair is used to train the network or generate the target image in the testing procedure. When compute the FID and LPIPS, the image size of "gt_image" in "gt_path" and "fid_real_image" in "fid_real_path" are 176*256, which are different with the generated image size with 256*256. Should I resize the image size of "gt_image" in "gt_path" and "fid_real_image" in "fid_real_path", then try to compute FID and LPIPS?

**Comment by RenYurui** [comment]
Hi,  we use 256256 images for training and test. 
We download the Highres version of the DeepFashion dataset and directly resize the images to 256256.
Please See [Pose-Guided Person Image Generation](https://github.com/RenYurui/Global-Flow-Local-Attention/blob/master/PERSON_IMAGE_GENERATION.md) for the dataset preparation.
