### ISSUE TITLE
Do DanceGenerator's source_previous and source_reference model can share params? 

### ISSUE THREAD

**Issue by ailias** [RenYurui/Global-Flow-Local-Attention#54]
Q1: Can we share source and flow model? 
     In DanceGenerator model, we have two source model and two flow model, and they only input different datas,  so can we only use one source and flow model to replace them?  The reason is the GPU memory consume too much to running it on 16g v100 machine. 

Q2: Why do we use unsupervised method for training flow net while not using pre-trained model for a better flow predictions?

**Comment by RenYurui** [comment]
Q1: yes, I think it is possible to share the parameters of the flow models in the DanceGenerator model. 
Q2: I think there are no suitable flow net models for these tasks. Most flow net models are proposed for adjacent frame flow prediction. The diversity of the input data will cause performance degradation. Meanwhile, model performance will be limited by the accuracy of the flow prediction.
