### ISSUE TITLE
animation_skeletons.rar seems loss

### ISSUE THREAD

**Issue by fizzf** [RenYurui/Global-Flow-Local-Attention#56]
Hi,
In the _**Pose-Guided Person Image Animation**_ part, When I run **_./script/download_animation_skeletons.sh_**, the file **_animation_skeletons.rar_** is  not available, could you please update the file link? Thanks!

**Comment by RenYurui** [comment]
Hi 
I can download the files successfully. 
Try to use this link: https://1drv.ws/u/s!ArirMHnmz_frlBeL5s8lQ6eCfsNb
