### ISSUE TITLE
Confusion about the usage of noise and clean pose data

### ISSUE THREAD

**Issue by ddlee-cn** [RenYurui/Global-Flow-Local-Attention#57]
Hi, I found that you use noise(openpose) pose for `ref_skeleton` and use clean(video2d) pose for the `gen_skeleton` in the dance_dataset. Could you please explain why? Why not use clean pose for both ref and target?

**Comment by RenYurui** [comment]
The reason is that our clean skeletons are extracted from image sequences. In theory, we cannot obtain the clean skeleton for the reference image.

**Comment by ddlee-cn** [comment]
I see. Thanks.
