### ISSUE TITLE
Domo Pose-Guided Person Image Generation not working

### ISSUE THREAD

**Issue by Peu-m** [RenYurui/Global-Flow-Local-Attention#58]
Hello,

I'm unable to run demo Person Image Generation.

here is my colab GPU architecture:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8    10W /  70W |      0MiB / 15079MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

I'm getting following error:
-------------------------------
Loading data pairs ...
Loading data pairs finished ...
dataset [FashionDataset] of size 41 was created
val images = 41
Network [PoseGenerator] was created. Total number of parameters: 14.0474 million. To see the architecture, do print(network).
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCTensorMathPairwise.cu line=225 error=11 : invalid argument
Traceback (most recent call last):
  File "demo.py", line 15, in <module>
    model = create_model(opt)

RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/generic/THCTensorMathPairwise.cu:225
---------------------------------

![image](https://user-images.githubusercontent.com/71484669/93562234-415fbc00-f9a3-11ea-8a4b-9b8e867b4e34.png)

Could you please suggest on how I can resolve this ?

**Comment by RenYurui** [comment]
The code has been tested with cuda9 and cuda10.0. I am not sure whether pytorch 1.0.0 can run with cuda 10.1.

**Comment by Peu-m** [comment]
Thank! for your prompt reply.

However, i also checked by installing cuda 10.0, issue remain same:
------------------------------
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/generic/THCTensorMathPairwise.cu:225
------------------------------
Original demo also uses Cuda 10.1 (screenshot attached)
![image](https://user-images.githubusercontent.com/71484669/93582650-6878b680-f9c0-11ea-9dc0-b92be0779951.png)

Therefore is the issue with GPU T-4 ?
------------------------------------
Note: The current code is tested with Tesla V100. If you use a different GPU, you may need to select correct nvcc_args for your GPU when you buil Custom CUDA Extensions. Comment or Uncomment --gencode in block_extractor/setup.py, local_attn_reshape/setup.py, and resample2d_package/setup.py. Please check here for details.
------------------------------------

**Comment by RenYurui** [comment]
Hi, I think it is a pytorch/cuda issue. 
Please check your env  (cuda10 and pytorch 1.0.0 for cuda10). 
If the problem persists see if you can run basic straight PyTorch examples such as https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html.
You may also need to set `torch.backends.cudnn.benchmark` to False if you do not use cudnn.

**Comment by Peu-m** [comment]
Thank You! for your reply, i will soon try and let you know on the above issue.

**Comment by Peu-m** [comment]
@RenYurui 
i tried to reset my colab env to get Tesla P100 GPU and by luck i got this GPU allocated for my runtime and found that code is working without any Error. 
Therefore, i think it is not pytorch and Cuda issue rather GPU architecture related issue.

I'm closing this issue as the demo code is working for Tesla P100 GPU.

Thank You
