### ISSUE TITLE
About the training data resolution

### ISSUE THREAD

**Issue by ChongjianGE** [RenYurui/Global-Flow-Local-Attention#59]
Hi @RenYurui ,
Thanks for the great work. 
I wonder what's the resolution of your training data?

**Comment by ChongjianGE** [comment]
Meanwhile, could you please help share the structure of the training data? Thank you.

**Comment by RenYurui** [comment]
I think you want to ask the resolution of the training images. 
We use 256 * 256 images for training. 
You can download the demo images to check the structure of the dataset by using ./download.sh
