### ISSUE TITLE
How to compute Openpose coordinates for new images ?

### ISSUE THREAD

**Issue by Peu-m** [RenYurui/Global-Flow-Local-Attention#60]
@RenYurui 

How to compute Openpose coordinates for new images ?
please guide.

Thank You

**Comment by Peu-m** [comment]
Sorry to rephrase my question here:

How to extract Alphapose with openpose format for new images to run demo.py for new images ?

Thank You

**Comment by mingliangfu** [comment]
> Sorry to rephrase my question here:
> 
> How to extract Alphapose with openpose format for new images to run demo.py for new images ?
> 
> Thank You

Hey, you should first make [the definition of key points](https://github.com/MVIG-SJTU/AlphaPose/blob/master/alphapose/utils/vis.py) clear.

**Comment by RenYurui** [comment]
Hi all, 
Sorry for the delay. I think this question is related to the output format of Alphapose. 
Please see the instruction of [Alphapose runing](https://github.com/MVIG-SJTU/AlphaPose/blob/0ad7db09e247bfe62ec04b009e58291ce6f26a66/docs/run.md)
You may need to set the `--format` when runing Alphapose.
