### ISSUE TITLE
about the FID and LPIPS is better than paper

### ISSUE THREAD

**Issue by Jarvisss** [RenYurui/Global-Flow-Local-Attention#70]
I got FID 9.87, and LPIPS 0.197 on DeepFashion, by running your pretrained model, which are better than you report in the paper, and I'm curious about why, could you plz explain about this difference?

**Comment by Jarvisss** [comment]
The test set I used contains 8570 images, and the images are resized to 256*256 follow your instruction in https://github.com/RenYurui/Global-Flow-Local-Attention/issues/53#issuecomment-669766733.

I wonder if the scores I got is correct, that you have made some improvements after the paper published, or I do something wrong.

Thanks!

**Comment by Jarvisss** [comment]
Maybe this is because different resize method, I tested Bilinear and Bicubic  interpolation, and find the FID has a large difference.
I wonder how are the ground truth images resized in your experiment? jpg or png? and bilinear or bicubic?
@RenYurui

**Comment by RenYurui** [comment]
The released models are the same. No improvements are made after the paper published. 
 We resize the original image as the ground truth image. Bicubic method and jpg file are used.

**Comment by cuiaiyu** [comment]
@Jarvisss Hi, may I ask if you have solved this problem? If so, how is it solved? I get exactly the same numbers of FID and LPIPS. Then we save the ground truth as 256x256 jpg images, but still get results better than reported. Thank you very much!
