### ISSUE TITLE
How is the key point detected

### ISSUE THREAD

**Issue by code-conquer** [RenYurui/Global-Flow-Local-Attention#72]
Hello, how do you get information about human key points that is not mentioned in this paper or on this website?

**Comment by RenYurui** [comment]
Hi, I think there are some instructions about how to download the key points. 
For the pose image generation task, we use the key points provided by https://github.com/tengteng95/Pose-Transfer. (extracted by Openpose)
For the animation task, the key points are extracted with the alphapose.
