### ISSUE TITLE
Urls in download.sh seem broken

### ISSUE THREAD

**Issue by cfanyyx** [RenYurui/Global-Flow-Local-Attention#77]
Could anyone provide Demo Images for me?

**Comment by KHao123** [comment]
Do you get these files?

**Comment by hzhao1997** [comment]
The same problem : (

**Comment by RenYurui** [comment]
Hi, 
Sorry for the problem. 
I will update the URLs tomorrow

**Comment by RenYurui** [comment]
The URLs have been updated.
