### ISSUE TITLE
The "Segmentation fault " problem when  run  "Pose-Guided Person Image Animation" task

### ISSUE THREAD

**Issue by MeaninglessAI** [RenYurui/Global-Flow-Local-Attention#83]
hi, no matter if I run the demo.py file in README.md or the test.py file in PERSON_IMAGE_ANIMATION.md() ,  there always occurs Segmentation fault problem. Hope somebody who can help me.

![image](https://user-images.githubusercontent.com/23152242/127617513-76a1ab9f-e576-4114-a9aa-11716b7735c8.png)

**Comment by MeaninglessAI** [comment]
> hi, no matter if I run the demo.py file in README.md or the test.py file in PERSON_IMAGE_ANIMATION.md() , there always occurs Segmentation fault problem. Hope somebody who can help me.
> 
> ![image](https://user-images.githubusercontent.com/23152242/127617513-76a1ab9f-e576-4114-a9aa-11716b7735c8.png)

after analysing by python package - faulthandler, the location of error is shown in the figure below:

![image](https://user-images.githubusercontent.com/23152242/127619675-e4006bba-2cae-4480-a184-1445693c99ad.png)


The corresponding code is shown in the figure below：

![image](https://user-images.githubusercontent.com/23152242/127619168-bcb9d60b-7a57-4a4c-9c81-deb4977befff.png)

Could somebody please suggest on how I can resolve this ?

**Comment by fengzz-coding** [comment]
Did you solve the problem? Can you tell me how you did it?
